// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ScToS6izz7pQW6TNTdKUFx4tccOuHpQ',
    appId: '1:736945986185:web:cb4f4b2bea9af688d54458',
    messagingSenderId: '736945986185',
    projectId: 'tiktok-e7a1a',
    authDomain: 'tiktok-e7a1a.firebaseapp.com',
    storageBucket: 'tiktok-e7a1a.firebasestorage.app',
    measurementId: 'G-LNK141YVXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCJ79eyDtb3CTKfkGI7y4mq00H4WFRelI',
    appId: '1:736945986185:android:d91ea19a5de763ddd54458',
    messagingSenderId: '736945986185',
    projectId: 'tiktok-e7a1a',
    storageBucket: 'tiktok-e7a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsh5T8wovZbVoEarwpk9TXTz7UjgOIT2Y',
    appId: '1:736945986185:ios:3a34af20ba68a5ffd54458',
    messagingSenderId: '736945986185',
    projectId: 'tiktok-e7a1a',
    storageBucket: 'tiktok-e7a1a.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClonee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsh5T8wovZbVoEarwpk9TXTz7UjgOIT2Y',
    appId: '1:736945986185:ios:3a34af20ba68a5ffd54458',
    messagingSenderId: '736945986185',
    projectId: 'tiktok-e7a1a',
    storageBucket: 'tiktok-e7a1a.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClonee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ScToS6izz7pQW6TNTdKUFx4tccOuHpQ',
    appId: '1:736945986185:web:0349163528c842f1d54458',
    messagingSenderId: '736945986185',
    projectId: 'tiktok-e7a1a',
    authDomain: 'tiktok-e7a1a.firebaseapp.com',
    storageBucket: 'tiktok-e7a1a.firebasestorage.app',
    measurementId: 'G-XKNZY5J5CJ',
  );
}
